name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
call-reusable-workflow:
  uses: ./.github/workflows/reusable-workflow.yml
  with:
    node: 14
    steps:
      - uses: actions/checkout@v4

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}"
